#!/bin/bash
#
# Print command line arguments one per line
#

#
# Print command line arguments one per line
#
count=1

while [ "$#" -ne 0 ]
do
      echo "$count : ""$1"
      count=$((count+1));
      shift
done

