#!/bin/bash

while getopts w name
do
         
        case $name in
          w)wopt=1;;
          
          *)echo "Invalid arg";;
        esac
done


if [[ ! -z $wopt ]];
  then
    search=$3;
    grep -A $2 -B $2 $3 $4;
   else
     search=$1;
     grep -A 1 -B 1 $1 $2;
   
fi
